<?php
echo '<html xmlns='http://www.w3.org/1999/xhtml' xmlns:b='http://www.google.com/2005/gml/b' xmlns:data='http://www.google.com/2005/gml/data' xmlns:expr='http://www.google.com/2005/gml/expr'>';
echo '<head>';
echo '<meta http-equiv='content-language' content='en-us'>';
echo '<meta content='width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0' name='viewport' />';
echo '<title>Torrentz2 Search Engine</title>';
echo '<meta property="og:description" content="torrent search engine, fast and most powerful torrent search engine online, with all latest content up to date">';
echo '<meta property="og:site_name" content="Torrentz2">';
echo '<meta name="twitter:site" content="@torrentz2">';
echo '<meta name="twitter:creator" content="@torrentz2">';
echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
echo '<meta content='IE=EmulateIE7' http-equiv='X-UA-Compatible' />';
echo '<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />';
echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
echo '<meta name="theme-color" content="#336699">';
echo '<meta name='msapplication-TileColor' content='#336699'>';
echo '<meta name="msapplication-navbutton-color" content="#336699">';
echo '<meta name="apple-mobile-web-app-status-bar-style" content="#336699">';
echo '<meta property="og:site_name" content="Torrentz - Torrent Search Engine" />';
echo '<meta property="og:type" content="website" />';
echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
echo '<meta name="keywords" content="torrentz2,torrentz ,meta search engine">';
echo '<meta name="theme-color" content="#336699">';
echo '<meta name='msapplication-TileColor' content='#336699'>';
echo '<meta name="msapplication-navbutton-color" content="#336699">';
echo '<meta name="apple-mobile-web-app-status-bar-style" content="#336699">';
echo '<meta property="og:site_name" content="Torrentz" />';
echo '<meta property="og:type" content="website" />';
echo '<meta content='IE=EmulateIE7' http-equiv='X-UA-Compatible' />';
echo '<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />';
echo '<meta content='torrentz2 search engine, search for games, latest movies, soundtracks, webseries and much more, torrentz2.eu' name='description' />';
echo '<meta content='Torrentz2 Search Engine' property='og:title' />';
echo '<meta content='torrentz2 search engine, search for games, latest movies, soundtracks, webseries and much more, torrentz2.eu' property='og:description' />';
echo '<!--[if IE]> <script> (function() { var html5 = ("abbr,article,aside,audio,canvas,datalist,details," + "figure,footer,header,hgroup,mark,menu,meter,nav,output," + "progress,section,time,video").split(','); for (var i = 0; i < html5.length; i++) { document.createElement(html5[i]); } try { document.execCommand('BackgroundImageCache', false, true); } catch(e) {} })(); </script> <![endif]-->';
echo '<style id='page-skin-1' type='text/css'><!--';
echo '/*';
echo 'body {';
echo 'font: $(body.font);';
echo 'color: $(body.text.color);';
echo 'background: $(body.background);';
echo 'padding: 0 $(content.shadow.spread) $(content.shadow.spread) $(content.shadow.spread);';
echo '$(body.background.override) margin: 0;';
echo 'padding: 0;';
echo '}';
echo '';
echo '--></style>';
echo '<meta name='google-adsense-platform-account' content='ca-host-pub-1556223355139109' />';
echo '<meta name='google-adsense-platform-domain' content='blogspot.com' />';
echo '</head>';
echo '<body>';
echo '<div class='main no-items section' id='main'>';
echo '</div>';
echo '<style>';
echo 'html{-webkit-text-size-adjust:none;-moz-text-size-adjust:none;-ms-text-size-adjust:none}*{margin:0;padding:0}body{font-family:Verdana,Tahoma,sans-serif;margin:0 auto}body a{color:#369;text-decoration:none}body a:hover,div.results a:hover,div.trackers a:hover,div.index-stats a:hover{color:#f51;text-decoration:underline}div.top{background-color:#369;border-radius:0 0 10px 10px;height:60px}div.top>h1>a{color:#fff;display:block;float:left;font-size:40px;font-weight:400;height:60px;text-align:center;text-decoration:none;padding:5px 20px}div.top>h1>a:hover{color:#b3cce6}div.top>ul{display:block;float:right;height:60px;list-style-type:none;padding-right:10px}div.top>ul>li{border-left:solid 1px #b3cce6;display:block;float:left;height:60px}div.top>ul>li>a{background-color:#369;color:#fff;display:block;float:left;font-size:20px;height:30px;padding:18px 18px 12px;text-decoration:none}div.top>ul>li>a:hover{background-color:#90b2d5;border-bottom:solid 10px #369;border-radius:0 0 5px 5px;color:#fff}div.footer{clear:both;font-size:10px;margin:40px 0 100px;text-align:center}div.note{background-color:#f1f2f3;border:solid 1px #97a6b5;border-radius:5px;color:#567;font-size:12px;line-height:20px;margin:20px;padding:10px 40px}p.generic{padding:10px;text-align:center}div.loader{background:#fff url(/img/loader2.gif) no-repeat center center;height:100px}form.search{background-color:#ffb090;border-radius:10px;display:block;margin:20px 0}form.search #thesearchbox{border:0;border-radius:5px;font-size:18px;margin:0;padding:4px;background:#fff url(/img/zoom.png) no-repeat;background-position:98% 50%;width:77%}form.search #thesearchbutton{background-color:#fff;border:0;border-radius:5px;color:#6b3f2e;cursor:pointer;font-size:18px;font-weight:700;height:30px;margin:0 0 0 1.5%;padding:0;width:20%}form.search>fieldset{border:none;display:block;height:30px;padding:10px}ul.autocomplete{background-color:#fff;border:solid 1px #ffb090;border-radius:4px;display:none;left:-100px;list-style-type:none;position:absolute;top:-100px}ul.autocomplete>li{border-top:solid 1px #ffb090;display:block;font-size:12px;padding:3px;text-align:left}ul.autocomplete>li.selected{background-color:#e1e1e1}@media(max-width:819px){body{width:99%;max-width:799px}#mgid{width:600px}div.results>dl>dt{width:100%;max-width:799px;min-width:600px;white-space:normal;min-height:40px}div.votebox,div.trackers{width:100%;float:none}div.index-stats>dl{width:100%;float:none}div.top{border-radius:0 0 10px 10px;height:50px}div.top>h1>a{font-size:32px;font-weight:400;height:50px;padding:5px 15px}div.top>ul{height:50px}div.top>ul>li{height:50px}div.top>ul>li>a{padding:13px 12px 7px}}@media(min-width:820px) and (max-width:1019px){body,#mgid{width:800px}div.results>dl>dt{width:460px}div.votebox,div.trackers{width:100%;float:none}}@media(min-width:1020px) and (max-width:1219px){body,#mgid{width:1000px}div.results>dl>dt{width:660px}}@media(min-width:1220px) and (max-width:1419px){body,#mgid{width:1200px}div.results>dl>dt{width:860px}}@media(min-width:1420px){body,#mgid{width:1400px}div.results>dl>dt{width:1060px}}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<div class="top">';
echo '<h1><a href="https://www.torrentz2.xyz" title="torrentz2">Torrentz<font color="#80b5de" size="small">2</font>';
echo '</a></h1>';
echo '<ul>';
echo '<li><a target="_blank" href="/cdn-cgi/l/email-protection#12607d7c647b7e617d7c5262607d667d7c7f737b7e3c717d7f18" title="Contact">Contact</a></li>';
echo '</ul>';
echo '</div>';
echo '';
echo '</script><script async src="https://cse.google.com/cse.js?cx=d71b788fa7389a0ee"></script>';
echo '<div class="gcse-search"></div>';
echo '<style type="text/css">';
echo '.gsc-control-cse{';
echo 'background-color: #FFB090;';
echo 'border-radius: 10px;';
echo 'display: block;';
echo 'margin: 20px 0;';
echo '}';
echo '.gsc-search-button{';
echo 'background-color: white;';
echo 'background-color: white;';
echo 'border-color: white;';
echo 'border-radius: 5px;';
echo '}';
echo '.gsc-search-button svg{';
echo 'fill:#6B3F2E;';
echo '}';
echo '.cse .gsc-search-button-v2, .gsc-search-button-v2{';
echo 'padding-top: -3px;';
echo 'padding-left: -10px;';
echo '}';
echo '';
echo '.gsc-search-button-v2:hover, .gsc-search-button-v2:focus{';
echo 'border-color: black;';
echo 'background-color: white;';
echo '}';
echo 'input.gsc-input {';
echo 'font-size: 24px;';
echo 'margin-top: -5px !important;';
echo 'border: 0;';
echo 'border-radius: 5px;';
echo 'font-size: 24;';
echo 'margin: 0;';
echo 'padding: 4px;';
echo '}';
echo '';
echo '.gsc-expansionArea{';
echo 'padding-bottom: 12px;';
echo 'background-color: white;';
echo '}';
echo '';
echo 'input.gsc-search-button {';
echo 'font-size: 18px;';
echo 'height: 37px;';
echo 'background-color: #FFF;';
echo 'border: 0;';
echo 'border-radius: 5px;';
echo 'color: #6B3F2E;';
echo 'cursor: pointer;';
echo 'font-weight: 700;';
echo 'width: 77%';
echo '}';
echo '';
echo '.gsc-search-box{';
echo 'background-color: #FFB090;';
echo 'border-radius: 10px;';
echo 'display: block';
echo '}';
echo '.gsc-input-box{';
echo 'background-color: #FFB090;';
echo 'border-color: #FFB090;';
echo 'border: none;';
echo '}';
echo '.gsc-input-box-hover {';
echo 'border: 0px solid #FFB090;';
echo 'border-top-color: #FFB090;';
echo '-moz-box-shadow: inset 0 0px 0px rgba(0,0,0,.1);';
echo '-webkit-box-shadow: inset 0 0px 0px rgba(0,0,0,.1);';
echo 'box-shadow: inset 0 0px 0px rgba(0,0,0,.1);';
echo 'outline: none;';
echo '}';
echo '';
echo '.gsc-search-box .gsc-input>input:focus,';
echo '.gsc-input-box-focus {';
echo 'border: 0px solid #FFB090;';
echo '-moz-box-shadow: inset 0 0px 0px rgba(0,0,0,.3);';
echo '-webkit-box-shadow: inset 0 0px 0px rgba(0,0,0,.3);';
echo 'box-shadow: inset 0 0px 0px rgba(0,0,0,.3);';
echo 'outline: none;';
echo '}';
echo '.cse .gsc-control-cse, .gsc-control-cse{';
echo 'padding:0.75em;';
echo 'padding-bottom: 0.25em;';
echo '}';
echo '';
echo '.help {';
echo 'font-size: 12px;';
echo 'margin: 0px 10px 20px 50px;';
echo 'line-height: 1.5em;';
echo '}';
echo '';
echo 'div#rr {';
echo 'color: red;';
echo 'padding-top:5px;';
echo 'font-size: small;';
echo '}';
echo '';
echo 'p.generic {';
echo 'padding: 2px;';
echo 'text-align: center;';
echo 'line-height: 1.6em;';
echo 'text-align: center;';
echo 'font-size: 17px;';
echo '}';
echo '';
echo 'div.footer {';
echo 'clear: both;';
echo 'font-size: 15px;';
echo 'margin: 40px 0 100px;';
echo 'text-align: center;';
echo '}';
echo '';
echo '</style>';
echo '<p class="generic"><a href="https://www.torrentz2.xyz">Torrentz2</a> is the most advanced search engine. torrentz2.eu is a free, fast and powerful meta-search engine combining results from dozens of search engines, Official meta search engine for active torrents.';
echo '</p>';
echo '<br>';
echo '';
echo '</div>';
echo '<p class="generic">Indexing 31,102,502 active torrents from 125,464,743 pages on 26 domains</p>';
echo '<br>';
echo '<center><a href="/"> Torrentz2 Mirror1 🔒</n> | <a href="/">Torrentz.eu mirror 🔒</a> | <a href="/" rel="follow">torrentz2-2fjsdhfhji.onion 🔒</a></center>';
echo '<br>';
echo '<table class="gstl_50 gssb_c" style="width: 1299px; display: none; top: 121px; position: absolute; left: 110px;" cellspacing="0" cellpadding="0"><tbody><tr><td class="gssb_f"></td><td class="gssb_e" style="width: 100%;"></td></tr></tbody></table>';
echo '</body>';
echo '</html>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>
